order_management:
  ocel_path: "files/databases/order_management.sqlite"
  graph_output_path: "files/graph_structures/order_management/"
  pytorch_path: 'files/hetero_structures/order_management/'
  model_output_path: 'files/models/order_management/'
  explainer_output_path: 'files/explainer_outputs/order_management/'
  viewpoint: "Orders"
  added_depth: 0
  unique_ids: ['Orders', 'Items', 'Packages']
  kpi_type: 0
  kpi_event: "PayOrder" #"CreatePackage" "PackageDelivered" "PayOrder"
  kpi_viewpoint: "Orders"
  batch_size: 16
  filtered_tables: ['object_object', 'event_object', 'event_map_type', 'object_map_type']
  attributes:
    Orders: ['price']
    Items: ['weight', 'price']
    Packages: ['weight']
  time_attributes:
    Products: ['weight', 'price'] # First value is the set attribute and the second one is the time sensitive one
  encoding: ['Customers', 'Employees']
  role_encoding:
    Employees: 'role'   # encode by role (Sales/Shipment/Warehousing → 3D) instead of OCEL_ID (18D)

logistics:
  ocel_path: "files/databases/logistics.sqlite"
  graph_output_path: "files/graph_structures/logistics/"
  pytorch_path: 'files/hetero_structures/logistics/'
  model_output_path: 'files/models/logistics/'
  explainer_output_path: 'files/explainer_outputs/logistics/'
  viewpoint: "CustomerOrder"
  added_depth: 2
  unique_ids: ['CustomerOrder', 'TransportDocument', 'Container', 'HandlingUnit']
  kpi_type: 0
  kpi_event: "LoadToVehicle" # Depart
  kpi_viewpoint: "CustomerOrder"
  batch_size: 16
  filtered_tables: ['object_object', 'event_object', 'event_map_type', 'object_map_type']
  attributes:
    CustomerOrder: ['AmountofGoods']
    Container: ['AmountofHandlingUnits', 'Weight']
    TransportDocument: ['AmountofContainers']
  time_attributes:
  encoding: ['HandlingUnit', 'Truck', 'Forklift', 'Vehicle']


aoe:
  viewpoint: "Session"
  added_depth: False
  ocel_path: "files/databases/aoe.sqlite"
  ev_output_path: "files/output_tables/aoe_ev_table.csv"
  ob_output_path: "files/output_tables/aoe_ob_table.csv"
  ocel_output_path: "files/output_tables/aoe_ocel.csv"
  filtered_tables: ['object_object', 'event_object', 'event_map_type', 'object_map_type']
  encoding: []


iot:
  viewpoint: "Pickupplan"
  added_depth: False
  ocel_path: "files/databases/CargoPickup_IoT.sqlite"
  ev_output_path: "files/output_tables/iot_ev_table.csv"
  ob_output_path: "files/output_tables/iot_ob_table.csv"
  ocel_output_path: "files/output_tables/iot_ocel.csv"
  filtered_tables: ['object_object', 'event_object', 'event_map_type', 'object_map_type', 'event_IoTobject', 'object_IoTobject']
  encoding: []